### ISSUE TITLE
nyc 15.x / next version of istanbul libraries

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/nyc#1104]
The following major/breaking changes are currently planned for nyc 15 and the next version of istanbul libraries:
* [x] Require Node.js 8 / drop Node.js 6
* [x] Expand default extension list (#1103)
* [x] Remove vestigial environmental variables (#1078)
* [x] Use [istanbul-lib-processinfo](https://github.com/istanbuljs/istanbul-lib-processinfo) from nyc
* [x] Use [@istanbuljs/load-nyc-config](https://github.com/istanbuljs/load-nyc-config) from nyc
* [x] Deprecate istanbul-api (istanbuljs/istanbuljs#378)
* [x] Redesign istanbul-lib-report summarizer API (istanbuljs/istanbuljs#390)
* [x] Remove config loading from test-exclude (istanbuljs/istanbuljs#392)
* [x] Use basename of source to construct cache filenames (istanbuljs/caching-transform#13)
* [x] New release of spawn-wrap (istanbuljs/spawn-wrap#90)
* [x] Resolve istanbul-reports regressions
* [x] Troubleshoot issue with `--all` run against pre-instrumented files (#1208)
* [ ] ~Find a solution for `nyc node --require esm` in latest versions of node.js~ Unfixable

This tracking ticket will be updated as progress is made, it will be closed when nyc@15.0.0 is released.

**Comment by coreyfarrell** [comment]
nyc 15.0.0-beta.0 is published to npm under the `next` tag, change-log pasted below.  babel-plugin-istanbul 6.0.0-beta.0 is also published to npm `next` tag.

---

### ⚠ BREAKING CHANGES

* The `flow` and `jsx` parser plugins are no longer
enabled by default.
* Node.js 8 is now required to run nyc
* Remove NYC_ROOT_ID and NYC_INSTRUMENTER environmental
variables.
* The `root` field has been removed from processinfo
files.

### Bug Fixes

* Avoid `source-map` module during `signal-exit` handler ([#1191](https://github.com/istanbuljs/nyc/issues/1191)) ([83eb629](https://github.com/istanbuljs/nyc/commit/83eb629))
* Drop coverage produced by `nyc --all` for files that were tested ([#1155](https://github.com/istanbuljs/nyc/issues/1155)) ([fc1bbbf](https://github.com/istanbuljs/nyc/commit/fc1bbbf)), closes [#1113](https://github.com/istanbuljs/nyc/issues/1113) [#1124](https://github.com/istanbuljs/nyc/issues/1124) [#1148](https://github.com/istanbuljs/nyc/issues/1148)
* Honor eager setting (false by default) ([#1179](https://github.com/istanbuljs/nyc/issues/1179)) ([c18fb0a](https://github.com/istanbuljs/nyc/commit/c18fb0a))
* Remove vestigial environment variables ([#1078](https://github.com/istanbuljs/nyc/issues/1078)) ([cfd3da0](https://github.com/istanbuljs/nyc/commit/cfd3da0))


### Features

* Add `--use-spawn-wrap=true` option ([#1169](https://github.com/istanbuljs/nyc/issues/1169)) ([df4de4d](https://github.com/istanbuljs/nyc/commit/df4de4d))
* Add `.cjs`, `.mjs`, `.ts`, `.tsx`, `.jsx` to default extensions ([#1110](https://github.com/istanbuljs/nyc/issues/1110)) ([914b776](https://github.com/istanbuljs/nyc/commit/914b776)), closes [#1103](https://github.com/istanbuljs/nyc/issues/1103)
* Allow `nyc instrument` to instrument code in place ([#1149](https://github.com/istanbuljs/nyc/issues/1149)) ([7783284](https://github.com/istanbuljs/nyc/commit/7783284))
* Drop node.js 6, upgrade dependencies ([#1134](https://github.com/istanbuljs/nyc/issues/1134)) ([00c3b34](https://github.com/istanbuljs/nyc/commit/00c3b34))
* Use @istanbuljs/schema for yargs setup ([#1194](https://github.com/istanbuljs/nyc/issues/1194)) ([fd40d49](https://github.com/istanbuljs/nyc/commit/fd40d49))
* Use istanbul-lib-processinfo ([#1145](https://github.com/istanbuljs/nyc/issues/1145)) ([7943413](https://github.com/istanbuljs/nyc/commit/7943413))
* Use source base name to prefix cache files ([#1144](https://github.com/istanbuljs/nyc/issues/1144)) ([5c1b7a9](https://github.com/istanbuljs/nyc/commit/5c1b7a9))

**Comment by mightyiam** [comment]
https://github.com/mightyiam/shields-badge-data/pull/120 :+1:

**Comment by coreyfarrell** [comment]
nyc 15.0.0-beta.1 is now published to npm `next` tag.  Updated change-log below.

---

### ⚠ BREAKING CHANGES

* The `flow` and `jsx` parser plugins are no longer
enabled by default.
* Node.js 8 is now required to run nyc
* Remove NYC_ROOT_ID and NYC_INSTRUMENTER environmental
variables.
* The `root` field has been removed from processinfo
files.

### Bug Fixes

* Avoid `source-map` module during `signal-exit` handler ([#1191](https://github.com/istanbuljs/nyc/issues/1191)) ([83eb629](https://github.com/istanbuljs/nyc/commit/83eb629))
* Correct handling of source-maps for pre-instrumented files ([#1216](https://github.com/istanbuljs/nyc/issues/1216)) ([8411a26](https://github.com/istanbuljs/nyc/commit/8411a26)), closes [#1208](https://github.com/istanbuljs/nyc/issues/1208)
* Drop coverage produced by `nyc --all` for files that were tested ([#1155](https://github.com/istanbuljs/nyc/issues/1155)) ([fc1bbbf](https://github.com/istanbuljs/nyc/commit/fc1bbbf)), closes [#1113](https://github.com/istanbuljs/nyc/issues/1113) [#1124](https://github.com/istanbuljs/nyc/issues/1124) [#1148](https://github.com/istanbuljs/nyc/issues/1148)
* Honor eager setting (false by default) ([#1179](https://github.com/istanbuljs/nyc/issues/1179)) ([c18fb0a](https://github.com/istanbuljs/nyc/commit/c18fb0a))
* Remove vestigial environment variables ([#1078](https://github.com/istanbuljs/nyc/issues/1078)) ([cfd3da0](https://github.com/istanbuljs/nyc/commit/cfd3da0))


### Features

* Add `--use-spawn-wrap=true` option ([#1169](https://github.com/istanbuljs/nyc/issues/1169)) ([df4de4d](https://github.com/istanbuljs/nyc/commit/df4de4d))
* Add `.cjs`, `.mjs`, `.ts`, `.tsx`, `.jsx` to default extensions ([#1110](https://github.com/istanbuljs/nyc/issues/1110)) ([914b776](https://github.com/istanbuljs/nyc/commit/914b776)), closes [#1103](https://github.com/istanbuljs/nyc/issues/1103)
* Allow `nyc instrument` to instrument code in place ([#1149](https://github.com/istanbuljs/nyc/issues/1149)) ([7783284](https://github.com/istanbuljs/nyc/commit/7783284))
* Drop node.js 6, upgrade dependencies ([#1134](https://github.com/istanbuljs/nyc/issues/1134)) ([00c3b34](https://github.com/istanbuljs/nyc/commit/00c3b34))
* Use @istanbuljs/schema for yargs setup ([#1194](https://github.com/istanbuljs/nyc/issues/1194)) ([fd40d49](https://github.com/istanbuljs/nyc/commit/fd40d49))
* Use istanbul-lib-processinfo ([#1145](https://github.com/istanbuljs/nyc/issues/1145)) ([7943413](https://github.com/istanbuljs/nyc/commit/7943413))
* Use source base name to prefix cache files ([#1144](https://github.com/istanbuljs/nyc/issues/1144)) ([5c1b7a9](https://github.com/istanbuljs/nyc/commit/5c1b7a9))

**Comment by coreyfarrell** [comment]
nyc 15.0.0 and babel-plugin-istanbul 6.0.0 are now published to npm under the `next` tag.  Some minor changes to reporting and some internal changes since the last update here.  Any testing would be appreciated, let me know of any issues.

The intent is for these to become the final releases.  CHANGELOG is now updated in the master branch.

**Comment by coreyfarrell** [comment]
nyc 15.0.0 and babel-plugin-istanbul 6.0.0 are now latest on npm.

**Comment by harpal-sgh** [comment]
I am getting 0% for statements, lines, functions - 
===================== Coverage summary ===============================
Statements   : 0% ( 0/34 )
Branches     : 100% ( 0/0 )
Functions    : 0% ( 0/4 )
Lines        : 0% ( 0/34 )
---------------------------------------------------------------------------------------------------------------------
nyc": "^15.0.0",

 "scripts": {
    "test": "serverless-bundle test",
    "test-nyc": "nyc npm test"
  },

I do have few tests for all the files.

**Comment by Codex-** [comment]
Had that as well but found it was a bad setting in `.nycrc` that we had from the old days
